spring:
  data:
    mongodb:
      uri: mongodb+srv://habeebcycle:secret101@cluster0-lzygs.mongodb.net/spring_mongo?retryWrites=true&w=majority
      database: spring_mongo

logging:
  level:
    root: DEBUG